name: Build and Publish

on:
  push:
    branches:
      - master

permissions:
  packages: write
  contents: read

env:
  Major: '1'
  Minor: '0'
  Version: '${{ github.run_number }}'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ github.token }}

      - name: Restore dependencies
        run: dotnet restore --no-cache --force-evaluate

      - name: Run tests
        run: dotnet test WebApi.sln --configuration Release --no-restore
        
      - name: Pack NuGet packages
        run: |
          dotnet pack Host/Host.csproj --configuration Release --no-restore --output packages /p:Version=${{ env.Major }}.${{ env.Minor }}.${{ env.Version }}
          dotnet pack Host.Testing/Host.Testing.csproj --configuration Release --no-restore --output packages /p:Version=${{ env.Major }}.${{ env.Minor }}.${{ env.Version }}

      - name: Push NuGet packages
        run: dotnet nuget push "packages/*.nupkg" --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --api-key ${{ github.token }} --skip-duplicate